Prevent restart with no server credentials which causes exit code 1
blackfireio/blackfire-cookbook pull request #9
Opened 2017-02-02 09:26 UTC by zaiddabaeen

This is a solution for someone who wants to install blackfire without setting the server credentials right away, such as in public vagrant boxes. Prior to this, on server restart, chef-solo would exit due to exit code 1 from the service restart operation, and the provisioning would fail.

2017-02-03 17:56 UTC, lyrixx commented on recipes/agent.rb
> +end
Could you fix the missing new line?

2017-02-03 18:09 UTC, tucksaun commented on recipes/agent.rb
> +if node[cookbook_name]['agent']['server_id'].empty? == false && node[cookbook_name]['agent']['server_token'].empty? == false
To me, using `only_if` or `not_if` looks more a chef way to do it

2017-02-03 18:26 UTC, zaiddabaeen commented
Using `not_if` guards now.

2017-02-06 09:53 UTC, lyrixx commented on recipes/agent.rb
> +end
Could you fix this missing return line ? thanks.

2017-02-06 10:09 UTC, tucksaun commented on recipes/agent.rb
> +end
Could you also remove the `.DS_Store` file ? Thanks

2017-02-06 10:14 UTC, zaiddabaeen commented
Fixed and merged all commits.

2017-02-06 11:04 UTC, zaiddabaeen commented
Done.

2017-02-06 11:32 UTC, lyrixx approved these changes

2017-02-06 11:45 UTC, tucksaun requested changes

2017-02-06 11:45 UTC, tucksaun commented on recipes/agent.rb
> +  not_if { node[cookbook_name]['agent']['server_token'].empty? }
one last thing: you also need to check for `nil?` before `empty?` as defaults are `nil` and not empty strings.

2017-02-07 17:13 UTC, tucksaun approved these changes

2017-02-07 17:17 UTC, tucksaun commented
Thanks @zaiddabaeen.

2017-02-07 17:18 UTC, closed without merging